### PR TITLE
Add fileutils_darwin to fix build on mac

### LINKED ISSUE #38: Fails to build on Mac
```
main.go:36:2: build constraints exclude all Go files in
/Users/xyz/f8a/mercator-go/src/github.com/fabric8-analytics/mercator-go/core/fileutils
```

```
# ls core/fileutils/
fileutils_linux.go  fileutils_windows.go
```

so we probably need also a `fileutils_mac.go` ?

CC @rootAvish

### PR DESCRIPTION
**Pull request by rootAvish**
Fixes #38.

### CODE REVIEW

**Comment by rootAvish** [comment]
[test]

**Comment by tisnik** [comment]
I don't know the context but what about filenames w/o paths?

```
.hidden_file
```

**Comment by rootAvish** [comment]
I just copy pasted the implementation that was there for fileutils_linux, if there's a change I think we should do it for all three. Or better yet have just the one file `fileutils.template` and during the build process copy it to `fileutils_{OS_NAME}.go` . What do you guys think?

**Comment by shaded-enmity** [comment]
@tisnik Might be worth documenting that the `IsHidden` function variants should be called on absolute paths (in the Windows case it doesn't matter but for the rest it does), like https://github.com/fabric8-analytics/mercator-go/blob/master/main.go#L239

**Comment by tisnik** [comment]
@shaded-enmity thanks for clarification!

**Pull request merged**
