### PR TITLE
Go Glide support

### PR DESCRIPTION
**Pull request by jpopelka**
related to https://github.com/openshiftio/openshift.io/issues/1406

### CODE REVIEW

**Comment by shaded-enmity** [comment]
One thing that might be worthwhile to implement is to pin down the dependency on `github.com/Masterminds/glide/cfg` so that upstream changes won't break your builds (perhaps use Glide itself for that lol).

**Comment by jpopelka** [comment]
Given [that](https://github.com/Masterminds/glide#golang-dep) "Glide will continue to be supported for some time but is considered to be in a state of support rather than active feature development." I don't expect any disruptive changes, but yeah, sure.

**Comment by msrb** [comment]
[test]

**Comment by msrb** [comment]
@jpopelka please rebase

**Comment by jpopelka** [comment]
[test]

**Comment by msrb** [comment]
[test]

**Pull request merged**
