### PR TITLE
Ignore unknown trigger lines in PKGINFO

### PR DESCRIPTION
**Pull request by msrb**

### CODE REVIEW

**Comment by msrb** [comment]
Fixes problem when unknown key-values pairs were appended to previous value, e.g.:

```shell
"license": "GPLv3+\nDescription-Content-Type: UNKNOWN"
```

**Comment by jpopelka** [comment]
Please also bump a [Release in mercator.spec](https://github.com/fabric8-analytics/mercator-go/blob/master/mercator.spec#L6) so that the new rpm is built in copr. LGTM otherwise 👍

**Comment by msrb** [comment]
Good catch, PTAL 😉

**Comment by jpopelka** [comment]
[Successful copr build](https://copr.fedorainfracloud.org/coprs/jpopelka/mercator/build/649250/)

**Pull request merged**
