### PR TITLE
Gopkg support

### PR DESCRIPTION
**Pull request by msrb**

### CODE REVIEW

**Comment by msrb** [comment]
@jpopelka 

> The handler doesn't look like golang code

And what would be the benefit of writing it in Golang? :)

**Comment by jpopelka** [comment]
You gaining some valuable experience :-)

**Comment by msrb** [comment]
I've heard, from the original author of Mercator, that Rust is better :) Look into it - something tells me that mercator-rust is right around the corner :P

**Comment by msrb** [comment]
Meh, timeout in CI, but all builds finished successfully: https://copr.fedorainfracloud.org/coprs/msrb/mercator-test/build/780801/

**Pull request merged**
