### PR TITLE
Separate Python, Ruby and NPM handler templates

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by fridex** [comment]
> LGTM, @fridex just one thing. Do you want to build it as RPM? If so, please bump specfile.

Not needed for my work, but if you want, I can do that :)

**Comment by pkajaba** [comment]
@fridex  It's ok then.

**Comment by jpopelka** [comment]
It'd make sense to also amend the [Makefile's install section](https://github.com/fabric8-analytics/mercator-go/blob/master/Makefile#L71) to not install **all** handlers from `handlers/`.

**Comment by fridex** [comment]
> It'd make sense to also amend the [Makefile's install section](https://github.com/fabric8-analytics/mercator-go/blob/master/Makefile#L71) to not install **all** handlers from `handlers/`.

Ah, missed that one. I will adjust it. Good catch!

**Comment by jpopelka** [comment]
Or maybe create separate folder for each handler under `handlers/` and each handler's Makefile would just copy the handler into `../` (i.e. into `handlers/`) ?

**Pull request merged**
